#!/usr/bin/env bash
# packaging/homebrew/generate-formula.sh
#
# Generates a Homebrew formula for opentelemetry-c from a source tarball.
#
# Usage:
#   ./packaging/homebrew/generate-formula.sh <tarball_url> <sha256>
#
# Where:
#   <tarball_url> is the URL of the source tarball (e.g., a GitHub release asset)
#   <sha256>      is the SHA-256 checksum of the tarball
#
# Example:
#   ./packaging/homebrew/generate-formula.sh \
#     https://github.com/otap-labs/opentelemetry-c/archive/refs/tags/v0.1.0.tar.gz \
#     <sha256-of-tarball>
#
# The generated formula is written to stdout. Redirect to a .rb file to save it.
#
# Prerequisites:
#   - Rust toolchain (rustup) must be available on the build system.
#   - CMake 3.21+.
#
# NOTE: Homebrew formula submission to homebrew-core requires a publicly
# accessible tarball with a verified SHA-256. This script is a TEMPLATE
# GENERATOR; the formula requires human review before submission.

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <tarball_url> <sha256>" >&2
    exit 1
fi

TARBALL_URL="$1"
SHA256="$2"

# Derive version from URL (e.g. v0.1.0 -> 0.1.0)
VERSION=$(echo "${TARBALL_URL}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1 | tr -d 'v')
if [[ -z "${VERSION}" ]]; then
    VERSION="0.1.0"
fi

cat <<EOF
# Generated by packaging/homebrew/generate-formula.sh
# Review before submitting to a Homebrew tap.

class OpentelemetryC < Formula
  desc "OpenTelemetry C API and SDK – Rust-backed C bindings"
  homepage "https://github.com/otap-labs/opentelemetry-c"
  url "${TARBALL_URL}"
  sha256 "${SHA256}"
  version "${VERSION}"
  license "Apache-2.0"
  head "https://github.com/otap-labs/opentelemetry-c.git", branch: "main"

  # Rust toolchain requirement.
  # Homebrew's rust formula provides a stable toolchain for the build.
  depends_on "rust" => :build
  depends_on "cmake" => :build
  depends_on "pkg-config" => :build

  # macOS and Linux only (no Windows).
  on_linux do
    depends_on "openssl@3"  # for native-tls on Linux
  end

  def install
    # Build with the default SDK features (native-tls + otlp-http).
    system "cmake", "-S", ".", "-B", "build",
           "-DCMAKE_BUILD_TYPE=Release",
           "-DCMAKE_INSTALL_PREFIX=#{prefix}",
           "-DOTEL_SDK_NATIVE_TLS=ON",
           *std_cmake_args

    system "cmake", "--build", "build", "--parallel"
    system "cmake", "--install", "build"
  end

  test do
    # Compile and run the minimal api_consumer test.
    (testpath/"test_otelc.c").write <<~C
      #include <opentelemetry_c/api.h>
      #include <stdio.h>
      int main(void) {
        otel_string_view_t v = otel_version_string();
        printf("version: %.*s\\n", (int)v.len, v.ptr);
        return 0;
      }
    C

    system ENV.cc, "-std=c11",
           "-I#{include}",
           testpath/"test_otelc.c",
           "-L#{lib}", "-lopentelemetry_c_api",
           "-o", testpath/"test_otelc"

    ENV["DYLD_LIBRARY_PATH"] = lib.to_s if OS.mac?
    ENV["LD_LIBRARY_PATH"] = lib.to_s if OS.linux?
    system testpath/"test_otelc"
  end
end
EOF
