name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: clusterfuzzlite-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Build AddressSanitizer fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          language: rust
          sanitizer: address
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fuzz changed code
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: code-change
          sanitizer: address
          output-sarif: true
          report-unreproducible-crashes: false
